// <auto-generated />
using Devabit.Telelingua.ReportingServices.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Devabit.Telelingua.ReportingServices.DataAccess.Migrations
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20180904143807_sixth")]
    partial class sixth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.ErrorQuery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Exception");

                    b.Property<string>("QueryText");

                    b.HasKey("Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.Query", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CategoryId");

                    b.Property<bool>("IsSqlEdited");

                    b.Property<string>("Name");

                    b.Property<string>("QueryText");

                    b.Property<string>("SqlQuery");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.SqlScript", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CategoryId");

                    b.Property<string>("Name");

                    b.Property<string>("SqlScriptText");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SqlScripts");
                });

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.Query", b =>
                {
                    b.HasOne("Devabit.Telelingua.ReportingServices.DataAccess.Models.Category", "Category")
                        .WithMany("Queries")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Devabit.Telelingua.ReportingServices.DataAccess.Models.SqlScript", b =>
                {
                    b.HasOne("Devabit.Telelingua.ReportingServices.DataAccess.Models.Category", "Category")
                        .WithMany("SqlScripts")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
