// Current user
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

// Import
export const IMPORT_FILE_SUCCESS = 'IMPORT_FILE_SUCCESS';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';

// Filters
export const GET_ALL_FILTER_USERS_SUCCESS = 'GET_ALL_FILTER_USERS_SUCCESS';
export const GET_ALL_FILTER_GROUPS_SUCCESS = 'GET_ALL_FILTER_GROUPS_SUCCESS';
export const GET_ALL_FILTER_STATUSES_SUCCESS = 'GET_ALL_FILTER_STATUSES_SUCCESS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_ALL_FILTER_LIST = 'CHANGE_ALL_FILTER_LIST';

// Tasks
export const GET_ALL_FILTERED_TASKS_SUCCESS = 'GET_ALL_FILTERED_TASKS_SUCCESS';
export const CHANGE_LOADED_TASK_STATUS = 'CHANGE_LOADED_TASK_STATUS';
export const LOAD_FILES_FOR_TASK_SUCCESS = 'LOAD_FILES_FOR_TASK_SUCCESS';
export const GET_ASSIGNEE_LIST_BY_TASK_SUCCESS = 'GET_ASSIGNEE_LIST_BY_TASK_SUCCESS';
export const REASSIGN_TASK_SUCCESS = 'REASSIGN_TASK_SUCCESS';
export const FINALIZE_TASK_SUCCESS = 'FINALIZE_TASK_SUCCESS';

// Config
export const TOGGLE_SORTABLE_LIST = 'TOGGLE_SORTABLE_LIST';
export const ON_SORT_COLUMN_END = 'ON_SORT_COLUMN_END';
export const CHANGE_OPENED_TASKS = 'CHANGE_OPENED_TASKS';
export const CHANGE_SORT_MATCHES = 'CHANGE_SORT_MATCHES';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
// Quality Survey
export const GET_SURVEY_BY_TASK_SUCCESS = 'GET_SURVEY_BY_TASK_SUCCESS';
export const SEND_SURVEY_BY_TASK_SUCCESS = 'SEND_SURVEY_BY_TASK_SUCCESS';